version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "80:80"
    volumes:
      - "./server:/app"
    environment:
      FLASK_DEBUG: "on"
      FLASK_APP: ./app.py
      FLASK_RUN_PORT: "80"
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - "./client/src:/app/src"
      - "/app/node_modules"
