name: CI

on:
  push:
  pull_request:

jobs:
  run-backend-tests:
    strategy:
      matrix:
        os: [macos-latest, "ubuntu-latest"]
        python-version:
          - "3.11"
    name: backend test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: pip3 install -r ./server/requirements.txt

      - name: Run tests
        working-directory: ./server
        run: pytest

  run-frontend-tests:
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
        node-version:
          - "20.x"
    name: frontend test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        working-directory: ./client
        run: npm install

      - name: Run tests
        working-directory: ./client
        run: npm test
